// GENERATED by experimental/duck_cuda/tools/generate_model_arm.py --variant kr240 --action-mode delta -- DO NOT EDIT.
// Fixed-base 6-axis arm, variant 'kr240' (B8/J6/P2 placeholder pairs), z-up frame,
// arm/arm_lowering.py (URDF-sourced KR240; 'lite' = 0.5 x length,
// 1/8 x mass Froude scaling). Every constant rounded once to float32.
// Shadows the duck header by include order (arm builds only).
// DW_ENV_KIND 1 (REACH) selects the kernel's reach policy layer; the
// DW_ENV_* / DW_RW_* / DW_GATE_* block pins walk/env/arm_reach.py,
// arm_reward.py and the frozen arm judge. FIXED BASE: DW_HINGE_PARENT[0]
// == 0, the static floor; body 1 is a decoupled phantom root
// (FEASIBILITY.md 1). Drift-checked by arm/tests/test_arm_serial_parity.py.
#ifndef DUCK_MODEL_H
#define DUCK_MODEL_H
#if defined(__CUDACC__)
#define DW_MODEL_CONST static __constant__ const
#else
#define DW_MODEL_CONST static const
#endif
#define DW_B 8   // bodies: floor 0 (+ fused base_link), phantom root 1, link_k = body k+1
#define DW_J 6   // revolute joints a1..a6
#define DW_N 12   // generalized dofs (6 phantom root + J)
#define DW_Q 13   // qpos width (root xyz + quat xyzw + J)
#define DW_JROWS 18        // 3*J joint row slots
#define DW_PAIRS 2         // kernel-mandated pairs: PLACEHOLDERS on link_1, never in contact
#define DW_MAXPOINTS 4
#define DW_MAXROWS 42      // 3*J + 3*DW_PAIRS*DW_MAXPOINTS
#define DW_FOOT_VERTS 8    // placeholder box corners
#define DW_DT 0.00200000009f  // duck-stack tick; 10 per 0.02 s step
#define DW_GRAVITY_Z -9.81000042f  // authored -9.81 (KR240 contract); humanoid is -20, NOT unified
#define DW_ARMATURE 0.0f       // not authored by the URDF
#define DW_DAMPING 0.0f  // URDF joint damping folded into DW_KV_TABLE
#define DW_FRICTION_LOSS 0.0f  // URDF Coulomb friction (<= 0.1 % of effort) dropped
// fp32 certificates, SCALE-AWARE: the certified humanoid lane's
// relative pins (1.75e-4 / 7e-3 / 2.4e-2 on its 2.72 N*s per-tick
// weight impulse) applied to this arm's reference impulse
// max(effort)*dt = 24 N*m*s.
#define DW_SOLVE_TOLERANCE 0.00153999997f
#define DW_MOMENTUM_TOLERANCE 0.0617999993f
#define DW_APGD_BUDGET 8192u
#define DW_TIER_CEILING 0.211999997f
// PD gains AUTHORED BY THE LOWERING (arm_lowering.gains: bandwidth
// sqrt(kp/I_max) >= 3 x the judge's 0.625 Hz target-change rate,
// gravity sag <= 0.01 rad at full horizontal extension, full torque
// within 0.1 rad, capped at sqrt(kp/I_min)*dt <= 0.25; kv = 2*0.7*
// sqrt(kp*I_max) + URDF damping). Scalars = MIN of the tables
// (dwc1_info summary only; the kernel consumes the tables).
#define DW_KP 1880.0f
#define DW_KV 33.0f
DW_MODEL_CONST float DW_KP_TABLE[DW_J] = {312000.0f,671000.0f,186000.0f,24500.0f,20000.0f,1880.0f};
DW_MODEL_CONST float DW_KV_TABLE[DW_J] = {37200.0f,44400.0f,9540.0f,419.0f,322.0f,33.0f};
#define DW_EFFORT_CAP 1200.0f
DW_MODEL_CONST float DW_EFFORT_CAP_TABLE[DW_J] = {12000.0f,12000.0f,9000.0f,3000.0f,2000.0f,1200.0f};
#define DW_FRICTION_D0 0.899999976f
#define DW_FRICTION_DWIDTH 0.949999988f
#define DW_FRICTION_TIMECONST 0.0199999996f
#define DW_LIMIT_MARGIN 0.0f
#define DW_LIMIT_TIMECONST 0.0199999996f
#define DW_LIMIT_DAMPRATIO 1.0f
DW_MODEL_CONST float DW_LIMIT_SOLIMP[5] = {0.899999976f,0.949999988f,0.00100000005f,0.5f,2.0f};
// body 1 = phantom root carrying base_link's mass/inertia (decoupled)
DW_MODEL_CONST float DW_BODY_MASS[DW_B] = {0.0f,430.0f,260.0f,180.0f,125.0f,65.0f,38.0f,22.0f};
DW_MODEL_CONST float DW_BODY_INERTIA[DW_B][3] = {{0.0f,0.0f,0.0f},{48.2050095f,70.7304764f,102.754593f},{24.9863815f,57.5017319f,50.3732338f},{11.600606f,62.8617554f,60.6344719f},{6.95017815f,29.1160393f,29.8230515f},{0.718545973f,1.405056f,1.40508902f},{0.714865029f,0.707022011f,0.959170997f},{0.120169997f,0.0622490011f,0.0622659996f}};
// joint 0 parent = 0: the STATIC FLOOR (structural weld)
DW_MODEL_CONST unsigned DW_HINGE_PARENT[DW_J] = {0,2,3,4,5,6};
DW_MODEL_CONST float DW_HINGE_AP[DW_J][3] = {{0.0f,0.0f,0.860625029f},{-0.416377008f,0.00286899996f,-0.155298993f},{0.756581008f,0.266732007f,0.00302900001f},{1.04295909f,-0.0761800036f,-0.007859f},{-0.106082f,0.0f,3.50000009e-05f},{-0.0586399995f,-0.0185410008f,2.99999992e-05f}};
DW_MODEL_CONST float DW_HINGE_AC[DW_J][3] = {{0.0298730005f,0.00286899996f,-0.155298993f},{-0.709668994f,0.266732007f,0.00302900001f},{-0.232041001f,-0.0761800036f,0.0444159992f},{-0.106082f,-0.0f,3.50000009e-05f},{-0.0586399995f,-0.0185410008f,2.99999992e-05f},{0.256886989f,-0.0f,4.19999997e-05f}};
DW_MODEL_CONST float DW_HINGE_AXIS[DW_J][3] = {{2.15390738e-15f,-4.64102072e-08f,-1.0f},{-4.64102072e-08f,1.0f,-4.64102072e-08f},{0.0f,1.0f,0.0f},{-1.0f,-4.64102072e-08f,0.0f},{4.64102072e-08f,-1.0f,0.0f},{-1.0f,-4.64102072e-08f,0.0f}};
DW_MODEL_CONST float DW_HINGE_REF[DW_J][4] = {{-2.32051036e-08f,1.0f,-2.32051036e-08f,5.38476844e-16f},{-2.32051036e-08f,1.0f,-2.32051036e-08f,5.38476844e-16f},{0.0f,0.0f,0.0f,1.0f},{-0.0f,-0.0f,-1.0f,2.32051036e-08f},{-0.0f,-0.0f,-1.0f,2.32051036e-08f},{-0.0f,-0.0f,-1.0f,2.32051036e-08f}};
DW_MODEL_CONST float DW_LIMIT_LOWER[DW_J] = {-3.22885919f,-2.70526004f,-2.26892805f,-6.10865259f,-2.26892805f,-6.10865259f};
DW_MODEL_CONST float DW_LIMIT_UPPER[DW_J] = {3.22885919f,0.610865176f,2.68780708f,6.10865259f,2.26892805f,6.10865259f};
// phantom root source->principal: base_link COM offset, no rotation
DW_MODEL_CONST float DW_ROOT_COM[3] = {-0.141742006f,0.0f,0.237581f};
DW_MODEL_CONST float DW_ROOT_QPC[4] = {0.0f,0.0f,0.0f,1.0f};
DW_MODEL_CONST float DW_REFERENCE_QPOS[DW_Q] = {0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,1.0f,0.0f,-1.20000005f,1.60000002f,0.0f,-0.400000006f,0.0f};
DW_MODEL_CONST float DW_INITIAL_QPOS[DW_Q] = {0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,1.0f,0.0f,-1.20000005f,1.60000002f,0.0f,-0.400000006f,0.0f};
DW_MODEL_CONST float DW_INITIAL_VEL[DW_N] = {0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f};
DW_MODEL_CONST float DW_HOME_TARGETS[DW_J] = {0.0f,-1.20000005f,1.60000002f,0.0f,-0.400000006f,0.0f};
DW_MODEL_CONST double DW_HOME_TARGETS_F64[DW_J] = {0,-1.2,1.6000000000000001,0,-0.40000000000000002,0};
// ---- DEVICE POLICY LAYER: DW_ENV_KIND_REACH (kernel ABI v8) ----
// walk/env/arm_reach.py contract, mirrored f64 in-kernel
#define DW_ENV_KIND 1   // DW_ENV_KIND_REACH
#define DW_ENV_ACTION_MODE 1   // DELTA: target += a * MAX_INC (clamped to limits); a = 0 holds
#define DW_ENV_OBS 27   // [q, QDOT*qd, target, tip, target-tip, prev action]
#define DW_ENV_ACT 6
#define DW_ENV_TICKS_PER_STEP 10u
#define DW_ENV_CONTROL_DT 0.02
#define DW_ENV_HORIZON_STEPS 400u
#define DW_ENV_QDOT_OBS_SCALE 0.25
#define DW_ENV_TIP_BODY 7      // link_6 (flange carrier)
#define DW_ENV_WRIST_BODY 6    // link_5 origin = a5 (judge wrist)
#define DW_ENV_ELBOW_BODY 4    // link_3 origin = a3 (judge elbow)
// tip = p_link6 + R (tool_xyz - com_link6); origins = p - R com (f64)
DW_MODEL_CONST double DW_ENV_TIP_OFFSET[3] = {-0.017113000000000045,0.0,4.2e-05};
DW_MODEL_CONST double DW_ENV_WRIST_COM[3] = {0.05864,0.018541,-3e-05};
DW_MODEL_CONST double DW_ENV_ELBOW_COM[3] = {0.232041,0.07618,-0.044416};
#define DW_ENV_REACH_M 3.461500099999997
#define DW_ENV_ACQ_RADIUS_M 0.02   // frozen judge
#define DW_ENV_ACQ_HOLD_STEPS 14u   // consecutive boundaries
#define DW_ENV_REACH_N_TARGETS 5   // == DWC1_REACH_TARGETS
// f64 env tables (arm_lowering.joint_limits / velocity_limits): the
// python env slews and clips with these, the physics with the f32 ones
DW_MODEL_CONST double DW_ENV_LIMIT_LOWER_F64[DW_J] = {-3.2288591,-2.7052601,-2.268928,-6.1086524,-2.268928,-6.1086524};
DW_MODEL_CONST double DW_ENV_LIMIT_UPPER_F64[DW_J] = {3.2288591,0.6108652,2.687807,6.1086524,2.268928,6.1086524};
DW_MODEL_CONST double DW_ENV_VELOCITY_LIMIT_F64[DW_J] = {1.797689,1.64061,1.745329,2.96706,2.251475,3.595378};
DW_MODEL_CONST double DW_ENV_MAX_TARGET_INCREMENT_F64[DW_J] = {0.035953780000000005,0.0328122,0.03490658,0.059341200000000004,0.0450295,0.07190756000000001};
// reward v5 (walk/env/arm_reward.py) -- the kernel's DW_RW_* block
#define DW_RW_VERSION 5
#define DW_RW_W_ALIVE 1.0
#define DW_RW_W_DIST 1.0
#define DW_RW_DIST_SIGMA_FRAC 0.1
#define DW_RW_W_SCALE 1.0
#define DW_RW_W_LIN 0.5
#define DW_RW_W_HOLD 1.0
#define DW_RW_W_ACQUIRE 10.0
#define DW_RW_W_TORQUE 0.05
#define DW_RW_W_SPEED 11.0
#define DW_RW_SPEED_FRAC 1.0
#define DW_RW_W_PROXY 10.0
#define DW_RW_N_DIST_SCALE_RADII 4
DW_MODEL_CONST double DW_RW_DIST_SCALE_RADII[4] = {1.0,2.0,4.0,8.0};
#define DW_RW_N_W_COMMAND_SPEED_J 6
DW_MODEL_CONST double DW_RW_W_COMMAND_SPEED_J[6] = {0.1,0.1,0.1,0.25,0.25,0.25};
#define DW_RW_N_W_ACTION_RATE_J 6
DW_MODEL_CONST double DW_RW_W_ACTION_RATE_J[6] = {0.05,0.05,0.05,0.2,0.2,0.2};
// FROZEN judge clause thresholds (walk/eval/arm_reach_judge.py) for the
// in-kernel judge-shadow counters and the proxy termination
#define DW_GATE_LIMIT_TOL_RAD 0.01
#define DW_GATE_SPEED_TOL_FRAC 1.0
#define DW_GATE_FLOOR_MARGIN_FRAC 0.05
#define DW_GATE_COLUMN_RADIUS_FRAC 0.2
#define DW_GATE_COLUMN_HEIGHT_FRAC 0.4
// placeholder pairs: link_1 (yaws only, box ~0.7 m above the floor)
DW_MODEL_CONST unsigned DW_PAIR_BODY_A[DW_PAIRS] = {2u,2u};
DW_MODEL_CONST unsigned DW_PAIR_BODY_B[DW_PAIRS] = {0u,0u};
DW_MODEL_CONST float DW_PAIR_MU[DW_PAIRS] = {0.600000024f,0.600000024f};
DW_MODEL_CONST float DW_FOOT_VERTICES[DW_PAIRS][DW_FOOT_VERTS][3] = {{{-0.100000001f,-0.100000001f,-0.100000001f},{0.100000001f,-0.100000001f,-0.100000001f},{-0.100000001f,0.100000001f,-0.100000001f},{0.100000001f,0.100000001f,-0.100000001f},{-0.100000001f,-0.100000001f,0.100000001f},{0.100000001f,-0.100000001f,0.100000001f},{-0.100000001f,0.100000001f,0.100000001f},{0.100000001f,0.100000001f,0.100000001f}},{{-0.100000001f,-0.100000001f,-0.100000001f},{0.100000001f,-0.100000001f,-0.100000001f},{-0.100000001f,0.100000001f,-0.100000001f},{0.100000001f,0.100000001f,-0.100000001f},{-0.100000001f,-0.100000001f,0.100000001f},{0.100000001f,-0.100000001f,0.100000001f},{-0.100000001f,0.100000001f,0.100000001f},{0.100000001f,0.100000001f,0.100000001f}}};
// ---- host-side contract pins (target sampler + judge episode shape;
// header-drift pinned so a python change must regenerate this header) ----
#define DW_ARM_VARIANT "kr240"
DW_MODEL_CONST double DW_ARM_HOME_TIP[3] = {2.4055530731170105,5.6852105185383916e-08,1.6825704209525858};
DW_MODEL_CONST double DW_ARM_TARGET_JOINT_BOX[DW_J][2] = {{-1.2,1.2},{-2.0,0.2},{0.4,2.2},{-0.6,0.6},{-1.6,1.6},{0.0,0.0}};
// feasibility tables (arm_lowering.inertia_scan over pose_grid)
DW_MODEL_CONST float DW_ARM_INERTIA_MAX[DW_J] = {2251.03467f,1492.93787f,246.636963f,3.23213291f,2.35174012f,0.120170042f};
DW_MODEL_CONST float DW_ARM_INERTIA_MIN[DW_J] = {191.928391f,559.86084f,220.887787f,1.56664431f,2.35174012f,0.120170042f};
DW_MODEL_CONST float DW_ARM_TAU_HOLD[DW_J] = {0.000402162492f,6706.77881f,1857.66711f,6.91172028f,77.3011703f,1.258328e-09f};
// FROZEN judge episode shape (walk/eval/arm_reach_judge.py)
#define DW_ARM_JUDGE_EPISODE_S 8.0
#define DW_ARM_JUDGE_ACQ_HOLD_S 0.25
DW_MODEL_CONST double DW_ARM_JUDGE_TIER_RADIUS_FRAC[3] = {0.15,0.3,0.4};
#endif
