"""Generate include/duck_model.h from the pinned duck lowering fixtures.

Reads the exact same sources the CPU oracle lane uses -- av.duck() (articulated
fixture: masses, principal inertias, hinge anchors/axes/reference quaternions,
PD/passive coefficients, joint limits, reference qpos) and
contact.Model (baked 18-vertex foot colliders, contact pairs, friction,
floor-clear reset frame) -- and emits every constant as float32 C literals.

The emitted header is committed; tests/test_serial_parity.py regenerates it
into a temporary file and fails on any drift, so the fp32 CUDA lane can never
silently diverge from the pinned model.

Usage: .venv/bin/python -B experimental/duck_cuda/tools/generate_model.py \
           [--output PATH]     (default: ../include/duck_model.h)
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[3]
DEFAULT_OUTPUT = Path(__file__).resolve().parents[1] / "include" / "duck_model.h"

FOOT_BODIES = (6, 15)          # left foot_assembly, right foot_assembly_2
FLOOR_PAIRS = (0, 1)           # cm.pairs indices: (left, right) foot vs floor


def f32(x) -> str:
    """Exact float32 C literal (9 significant digits round-trips binary32)."""
    v = float(np.float32(x))
    if v == int(v) and abs(v) < 1e9:
        return f"{v:.1f}f"
    return f"{np.float32(x):.9g}f"


def row(values) -> str:
    return "{" + ",".join(f32(v) for v in values) + "}"


def load_fixture():
    sys.path.insert(0, str(ROOT / "walk" / "env"))
    import native_lane

    lib_path = native_lane.build_library()
    native = native_lane._native()
    fixture = native.av.duck()
    cm = native.contact.Model(native.contact.library(str(lib_path)))
    return native, fixture, cm


def emit(native, fixture, cm) -> str:
    J, B = fixture.J, fixture.B
    assert (J, B) == (14, 16)
    frame = cm.record["frames"][0]
    base = np.array([*frame["base_pose"][:3], *frame["base_pose"][4:],
                     frame["base_pose"][3], *frame["joint_q"]])
    assert base[2] == 0.16788827542191784, "floor-clear reset pin mismatch"
    vel = np.array(frame["qvel"], dtype="d")
    vel[3:6] = native.av.rot(base[3:7]) @ vel[3:6]

    limits = native.av.limits(fixture)
    h0 = fixture.hinge[0]
    shared = dict(armature=h0.armature, damping=h0.damping, loss=h0.loss,
                  kp=h0.kp, kv=h0.kv, cap=h0.cap, d0=h0.d0, dw=h0.dw, tc=h0.tc)
    for h in fixture.hinge:
        assert h.motor_enabled == 1
        for name, value in shared.items():
            assert getattr(h, name) == value, f"per-joint {name} drift"
    for lim in limits:
        assert lim.enabled == 1 and lim.margin == 0.0
        assert lim.timeconst == 0.02 and lim.dampratio == 1.0
        assert list(lim.solimp) == [0.9, 0.95, 0.001, 0.5, 2.0]

    pairs = [(p.body_a, p.body_b) for p in cm.pairs]
    assert pairs[:2] == [(6, 0), (15, 0)], "foot-vs-floor pair order drift"
    assert list(np.float32(cm.mu[:2])) == [np.float32(0.6)] * 2
    floor = cm.shapes[0]
    assert floor.kind == 2 and floor.fixed == 1
    assert list(floor.plane_normal) == [0.0, 0.0, 1.0] and floor.plane_offset == 0.0
    for b in FOOT_BODIES:
        assert cm.shapes[b].kind == 1 and cm.shapes[b].vertex_count == 18

    lines = [
        "// GENERATED by experimental/duck_cuda/tools/generate_model.py -- DO NOT EDIT.",
        "// Pinned Open Duck plain-14 lowering (see native.duck_scene / native.av.duck()),",
        "// every constant rounded once to float32. Drift-checked by test_serial_parity.py.",
        "#ifndef DUCK_MODEL_H",
        "#define DUCK_MODEL_H",
        "// __constant__ puts the model tables in device constant memory (well",
        "// under the 64 KB budget); host builds see plain static const.",
        "#if defined(__CUDACC__)",
        "#define DW_MODEL_CONST static __constant__ const",
        "#else",
        "#define DW_MODEL_CONST static const",
        "#endif",
        "#define DW_B 16   // bodies: floor 0, root 1, hinge children j+2",
        "#define DW_J 14   // hinge joints",
        "#define DW_N 20   // generalized dofs (6 root + J)",
        "#define DW_Q 21   // qpos width (root xyz + quat xyzw + J)",
        "#define DW_JROWS 42        // 3*J joint row slots: friction, lower, upper",
        "#define DW_PAIRS 2         // foot-vs-floor contact pairs (L, R)",
        "#define DW_MAXPOINTS 4     // manifold points per pair",
        "#define DW_MAXROWS 66      // 3*J + 3*DW_PAIRS*DW_MAXPOINTS",
        "#define DW_FOOT_VERTS 18   // baked convex sole vertices per foot",
        f"#define DW_DT {f32(0.002)}",
        f"#define DW_GRAVITY_Z {f32(-9.81)}",
        f"#define DW_ARMATURE {f32(shared['armature'])}",
        f"#define DW_DAMPING {f32(shared['damping'])}",
        f"#define DW_FRICTION_LOSS {f32(shared['loss'])}",
        f"#define DW_KP {f32(shared['kp'])}",
        f"#define DW_KV {f32(shared['kv'])}",
        f"#define DW_EFFORT_CAP {f32(shared['cap'])}",
        f"#define DW_FRICTION_D0 {f32(shared['d0'])}",
        f"#define DW_FRICTION_DWIDTH {f32(shared['dw'])}",
        f"#define DW_FRICTION_TIMECONST {f32(shared['tc'])}",
        f"#define DW_LIMIT_MARGIN {f32(0.0)}",
        f"#define DW_LIMIT_TIMECONST {f32(0.02)}",
        f"#define DW_LIMIT_DAMPRATIO {f32(1.0)}",
        "DW_MODEL_CONST float DW_LIMIT_SOLIMP[5] = "
        + row([0.9, 0.95, 0.001, 0.5, 2.0]) + ";",
        "DW_MODEL_CONST float DW_BODY_MASS[DW_B] = "
        + row([fixture.body[b].mass for b in range(B)]) + ";",
        "DW_MODEL_CONST float DW_BODY_INERTIA[DW_B][3] = {"
        + ",".join(row(list(fixture.body[b].inertia)) for b in range(B)) + "};",
        "DW_MODEL_CONST unsigned DW_HINGE_PARENT[DW_J] = {"
        + ",".join(str(h.parent) for h in fixture.hinge) + "};",
        "DW_MODEL_CONST float DW_HINGE_AP[DW_J][3] = {"
        + ",".join(row(list(h.ap)) for h in fixture.hinge) + "};",
        "DW_MODEL_CONST float DW_HINGE_AC[DW_J][3] = {"
        + ",".join(row(list(h.ac)) for h in fixture.hinge) + "};",
        "DW_MODEL_CONST float DW_HINGE_AXIS[DW_J][3] = {"
        + ",".join(row(list(h.axis)) for h in fixture.hinge) + "};",
        "DW_MODEL_CONST float DW_HINGE_REF[DW_J][4] = {"
        + ",".join(row(list(h.reference)) for h in fixture.hinge) + "};",
        "DW_MODEL_CONST float DW_LIMIT_LOWER[DW_J] = "
        + row([l.lower for l in limits]) + ";",
        "DW_MODEL_CONST float DW_LIMIT_UPPER[DW_J] = "
        + row([l.upper for l in limits]) + ";",
        "DW_MODEL_CONST float DW_ROOT_COM[3] = "
        + row(list(fixture.model.root_inertia)[:3]) + ";",
        "DW_MODEL_CONST float DW_ROOT_QPC[4] = "
        + row(list(fixture.model.root_inertia)[3:7]) + ";",
        "DW_MODEL_CONST float DW_REFERENCE_QPOS[DW_Q] = "
        + row(list(fixture.reference)) + ";",
        "DW_MODEL_CONST float DW_INITIAL_QPOS[DW_Q] = " + row(base) + ";",
        "DW_MODEL_CONST float DW_INITIAL_VEL[DW_N] = " + row(vel) + ";",
        "DW_MODEL_CONST float DW_HOME_TARGETS[DW_J] = "
        + row(frame["motor_targets"]) + ";",
        "// exact f64 home targets: the device policy layer's action->target",
        "// chain runs in f64 to mirror walk/env/flat.py's HOME bit for bit.",
        "DW_MODEL_CONST double DW_HOME_TARGETS_F64[DW_J] = {"
        + ",".join(f"{float(x):.17g}" for x in frame["motor_targets"]) + "};",
        "DW_MODEL_CONST unsigned DW_PAIR_BODY_A[DW_PAIRS] = {6u,15u};",
        "DW_MODEL_CONST unsigned DW_PAIR_BODY_B[DW_PAIRS] = {0u,0u};",
        "DW_MODEL_CONST float DW_PAIR_MU[DW_PAIRS] = " + row(cm.mu[:2]) + ";",
        "DW_MODEL_CONST float DW_FOOT_VERTICES[DW_PAIRS][DW_FOOT_VERTS][3] = {"
        + ",".join(
            "{" + ",".join(row(list(cm.shapes[b].vertices[i])) for i in range(18)) + "}"
            for b in FOOT_BODIES) + "};",
        "#endif",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    native, fixture, cm = load_fixture()
    text = emit(native, fixture, cm)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text)
    print(f"wrote {args.output} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
