"""Generate arm/include/<variant>/duck_model.h from the arm lowering.

The arm twin of generate_model_humanoid.py (generate_model.py and the
humanoid generator are UNTOUCHED): emits the same DW_* macro/table surface
the single-source kernel (src/duck_cuda_kernel.h) consumes, with the arm
variant's values from arm/arm_lowering.py -- every constant rounded once to
float32. Emitted headers are committed under arm/include/<variant>/ and
drift-checked by arm/tests/test_arm_serial_parity.py.

The file is deliberately named duck_model.h: the kernel includes
"duck_model.h", and the arm serial build (walk/env/arm_cuda_lane.py) passes
-Iarm/include/<variant> AHEAD of -Iexperimental/duck_cuda/include so this
header shadows the duck's without touching any kernel source.

PHYSICS + DEVICE POLICY LAYER. The physics tables drive the dwc1 physics
path (dwc1_create/step/read/reset/set_state). `#define DW_ENV_KIND 1`
(DW_ENV_KIND_REACH, kernel ABI v8) selects the kernel's REACH policy layer
-- dwc1_step_policy / dwc1_observe / dwc1_reset_policy / dwc1_reach_* --
whose every constant is emitted here from the python contract: the env
(walk/env/arm_reach.py: OBS 27, limit-scaled slew, acquisition hold), the
reward (walk/env/arm_reward.py -> DW_RW_*), and the FROZEN judge's clause
thresholds (walk/eval/arm_reach_judge.py -> DW_GATE_*, DW_ENV_ACQ_*), so
any python-side change fails the header-drift test until regenerated
(arm/tests/test_arm_serial_parity.py) and the device path is parity-tested
against the python env (arm/tests/test_arm_device_policy.py). Duck and
humanoid headers omit DW_ENV_KIND and compile the unchanged locomotion
layer (DW_ENV_KIND_LOCOMOTION is the kernel default).

FIXED BASE: DW_HINGE_PARENT[0] = 0 (the static floor) -- see
arm/FEASIBILITY.md section 1; body 1 is the decoupled phantom root.

Usage: .venv/bin/python -B experimental/duck_cuda/tools/generate_model_arm.py \
           --variant {kr240,lite} [--output PATH]
       (default output: <repo>/arm/include/<variant>/duck_model.h)
"""
from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[3]


def f32(x) -> str:
    """Exact float32 C literal (9 significant digits round-trips binary32)."""
    v = float(np.float32(x))
    if v == int(v) and abs(v) < 1e9:
        return f"{v:.1f}f"
    return f"{np.float32(x):.9g}f"


def row(values) -> str:
    return "{" + ",".join(f32(v) for v in values) + "}"


def f64row(values) -> str:
    """Exact float64 C literals (repr round-trips binary64)."""
    return ",".join(f"{float(v)!r}" for v in values)


def load_lowering():
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))
    if str(ROOT / "arm") not in sys.path:
        sys.path.insert(0, str(ROOT / "arm"))
    import arm_lowering  # noqa: PLC0415
    return arm_lowering


def default_output(variant: str) -> Path:
    return ROOT / "arm" / "include" / variant / "duck_model.h"


def emit(al, variant: str) -> str:
    from walk.env import arm_reach as env_mod  # noqa: PLC0415
    from walk.env import arm_reward as reward_mod  # noqa: PLC0415
    from walk.eval import arm_reach_judge as judge  # noqa: PLC0415 (frozen)

    s = al.spec(variant)
    J, B = al.J, al.B
    n, q = 6 + J, 7 + J
    jrows, maxrows = 3 * J, 3 * J + 3 * 2 * 4
    rows = al.hinge_rows(s, kernel=True)
    kp, kv = al.gains(s)
    caps = list(al.effort(s))
    cert = al.certificates(s)
    reset_q = al.reset_qpos(s)
    verts = al.placeholder_vertices(s)
    home_tip = al.home_tip(s)
    i_max, i_min, tau_hold = al.inertia_scan(s)
    lim = al.joint_limits(s)
    vlim = al.velocity_limits(s)
    tip_off = np.asarray(s.tool_xyz) - np.asarray(s.links[-1].com)   # f64
    assert al.TIP_BODY == 1 + J and al.LINK_BODIES == tuple(range(2, 2 + J))
    lines = [
        "// GENERATED by experimental/duck_cuda/tools/generate_model_arm.py"
        f" --variant {variant} -- DO NOT EDIT.",
        f"// Fixed-base 6-axis arm, variant '{variant}' (B8/J6/P2 placeholder"
        " pairs), z-up frame,",
        "// arm/arm_lowering.py (URDF-sourced KR240; 'lite' = 0.5 x length,",
        "// 1/8 x mass Froude scaling). Every constant rounded once to float32.",
        "// Shadows the duck header by include order (arm builds only).",
        "// DW_ENV_KIND 1 (REACH) selects the kernel's reach policy layer; the",
        "// DW_ENV_* / DW_RW_* / DW_GATE_* block pins walk/env/arm_reach.py,",
        "// arm_reward.py and the frozen arm judge. FIXED BASE: DW_HINGE_PARENT[0]",
        "// == 0, the static floor; body 1 is a decoupled phantom root",
        "// (FEASIBILITY.md 1). Drift-checked by arm/tests/test_arm_serial_parity.py.",
        "#ifndef DUCK_MODEL_H",
        "#define DUCK_MODEL_H",
        "#if defined(__CUDACC__)",
        "#define DW_MODEL_CONST static __constant__ const",
        "#else",
        "#define DW_MODEL_CONST static const",
        "#endif",
        f"#define DW_B {B}   // bodies: floor 0 (+ fused base_link), phantom root 1, link_k = body k+1",
        f"#define DW_J {J}   // revolute joints a1..a6",
        f"#define DW_N {n}   // generalized dofs (6 phantom root + J)",
        f"#define DW_Q {q}   // qpos width (root xyz + quat xyzw + J)",
        f"#define DW_JROWS {jrows}        // 3*J joint row slots",
        "#define DW_PAIRS 2         // kernel-mandated pairs: PLACEHOLDERS on link_1, never in contact",
        "#define DW_MAXPOINTS 4",
        f"#define DW_MAXROWS {maxrows}      // 3*J + 3*DW_PAIRS*DW_MAXPOINTS",
        "#define DW_FOOT_VERTS 8    // placeholder box corners",
        f"#define DW_DT {f32(al.SIM_DT)}  // duck-stack tick; 10 per 0.02 s step",
        f"#define DW_GRAVITY_Z {f32(-al.GRAVITY)}  // authored -9.81 (KR240 contract); humanoid is -20, NOT unified",
        f"#define DW_ARMATURE {f32(al.ARMATURE)}       // not authored by the URDF",
        f"#define DW_DAMPING {f32(al.PASSIVE_DAMPING)}  // URDF joint damping folded into DW_KV_TABLE",
        f"#define DW_FRICTION_LOSS {f32(al.FRICTION_LOSS)}  // URDF Coulomb friction (<= 0.1 % of effort) dropped",
        "// fp32 certificates, SCALE-AWARE: the certified humanoid lane's",
        "// relative pins (1.75e-4 / 7e-3 / 2.4e-2 on its 2.72 N*s per-tick",
        "// weight impulse) applied to this arm's reference impulse",
        f"// max(effort)*dt = {cert['reference_impulse']:.6g} N*m*s.",
        f"#define DW_SOLVE_TOLERANCE {f32(cert['solve_tolerance'])}",
        f"#define DW_MOMENTUM_TOLERANCE {f32(cert['momentum_tolerance'])}",
        "#define DW_APGD_BUDGET 8192u",
        f"#define DW_TIER_CEILING {f32(cert['tier_ceiling'])}",
        "// PD gains AUTHORED BY THE LOWERING (arm_lowering.gains: bandwidth",
        "// sqrt(kp/I_max) >= 3 x the judge's 0.625 Hz target-change rate,",
        "// gravity sag <= 0.01 rad at full horizontal extension, full torque",
        "// within 0.1 rad, capped at sqrt(kp/I_min)*dt <= 0.25; kv = 2*0.7*",
        "// sqrt(kp*I_max) + URDF damping). Scalars = MIN of the tables",
        "// (dwc1_info summary only; the kernel consumes the tables).",
        f"#define DW_KP {f32(min(kp))}",
        f"#define DW_KV {f32(min(kv))}",
        "DW_MODEL_CONST float DW_KP_TABLE[DW_J] = " + row(kp) + ";",
        "DW_MODEL_CONST float DW_KV_TABLE[DW_J] = " + row(kv) + ";",
        f"#define DW_EFFORT_CAP {f32(min(caps))}",
        "DW_MODEL_CONST float DW_EFFORT_CAP_TABLE[DW_J] = " + row(caps) + ";",
        f"#define DW_FRICTION_D0 {f32(al.FRICTION_D0)}",
        f"#define DW_FRICTION_DWIDTH {f32(al.FRICTION_DWIDTH)}",
        f"#define DW_FRICTION_TIMECONST {f32(al.FRICTION_TIMECONST)}",
        f"#define DW_LIMIT_MARGIN {f32(al.LIMIT_MARGIN)}",
        f"#define DW_LIMIT_TIMECONST {f32(al.LIMIT_TIMECONST)}",
        f"#define DW_LIMIT_DAMPRATIO {f32(al.LIMIT_DAMPRATIO)}",
        "DW_MODEL_CONST float DW_LIMIT_SOLIMP[5] = " + row(al.LIMIT_SOLIMP) + ";",
        "// body 1 = phantom root carrying base_link's mass/inertia (decoupled)",
        "DW_MODEL_CONST float DW_BODY_MASS[DW_B] = " + row(al.body_masses(s)) + ";",
        "DW_MODEL_CONST float DW_BODY_INERTIA[DW_B][3] = {"
        + ",".join(row(i3) for i3 in al.body_inertias(s)) + "};",
        "// joint 0 parent = 0: the STATIC FLOOR (structural weld)",
        "DW_MODEL_CONST unsigned DW_HINGE_PARENT[DW_J] = {"
        + ",".join(str(r[0]) for r in rows) + "};",
        "DW_MODEL_CONST float DW_HINGE_AP[DW_J][3] = {"
        + ",".join(row(r[1]) for r in rows) + "};",
        "DW_MODEL_CONST float DW_HINGE_AC[DW_J][3] = {"
        + ",".join(row(r[2]) for r in rows) + "};",
        "DW_MODEL_CONST float DW_HINGE_AXIS[DW_J][3] = {"
        + ",".join(row(r[3]) for r in rows) + "};",
        "DW_MODEL_CONST float DW_HINGE_REF[DW_J][4] = {"
        + ",".join(row(r[4]) for r in rows) + "};",
        "DW_MODEL_CONST float DW_LIMIT_LOWER[DW_J] = " + row(lim[:, 0]) + ";",
        "DW_MODEL_CONST float DW_LIMIT_UPPER[DW_J] = " + row(lim[:, 1]) + ";",
        "// phantom root source->principal: base_link COM offset, no rotation",
        "DW_MODEL_CONST float DW_ROOT_COM[3] = " + row(s.base.com) + ";",
        "DW_MODEL_CONST float DW_ROOT_QPC[4] = " + row([0.0, 0.0, 0.0, 1.0]) + ";",
        "DW_MODEL_CONST float DW_REFERENCE_QPOS[DW_Q] = " + row(reset_q) + ";",
        "DW_MODEL_CONST float DW_INITIAL_QPOS[DW_Q] = " + row(reset_q) + ";",
        "DW_MODEL_CONST float DW_INITIAL_VEL[DW_N] = " + row([0.0] * n) + ";",
        "DW_MODEL_CONST float DW_HOME_TARGETS[DW_J] = " + row(s.home_q) + ";",
        "DW_MODEL_CONST double DW_HOME_TARGETS_F64[DW_J] = {"
        + ",".join(f"{float(x):.17g}" for x in s.home_q) + "};",
        "// ---- DEVICE POLICY LAYER: DW_ENV_KIND_REACH (kernel ABI v8) ----",
        "// walk/env/arm_reach.py contract, mirrored f64 in-kernel",
        "#define DW_ENV_KIND 1   // DW_ENV_KIND_REACH",
        f"#define DW_ENV_OBS {int(env_mod.OBS)}   // [q, QDOT*qd, target, tip, target-tip, prev action]",
        f"#define DW_ENV_ACT {int(env_mod.ACT)}",
        f"#define DW_ENV_TICKS_PER_STEP {int(env_mod.TICKS_PER_STEP)}u",
        f"#define DW_ENV_CONTROL_DT {float(al.CONTROL_DT)!r}",
        f"#define DW_ENV_HORIZON_STEPS {int(env_mod.HORIZON_STEPS)}u",
        f"#define DW_ENV_QDOT_OBS_SCALE {float(env_mod.QDOT_OBS_SCALE)!r}",
        f"#define DW_ENV_TIP_BODY {al.TIP_BODY}      // link_6 (flange carrier)",
        f"#define DW_ENV_WRIST_BODY {al.LINK_BODIES[4]}    // link_5 origin = a5 (judge wrist)",
        f"#define DW_ENV_ELBOW_BODY {al.LINK_BODIES[2]}    // link_3 origin = a3 (judge elbow)",
        "// tip = p_link6 + R (tool_xyz - com_link6); origins = p - R com (f64)",
        "DW_MODEL_CONST double DW_ENV_TIP_OFFSET[3] = {" + f64row(tip_off) + "};",
        "DW_MODEL_CONST double DW_ENV_WRIST_COM[3] = {" + f64row(s.links[4].com) + "};",
        "DW_MODEL_CONST double DW_ENV_ELBOW_COM[3] = {" + f64row(s.links[2].com) + "};",
        f"#define DW_ENV_REACH_M {float(al.reach(s))!r}",
        f"#define DW_ENV_ACQ_RADIUS_M {float(judge.ACQ_RADIUS_M[variant])!r}   // frozen judge",
        f"#define DW_ENV_ACQ_HOLD_STEPS {int(env_mod.ACQ_HOLD_STEPS)}u   // consecutive boundaries",
        f"#define DW_ENV_REACH_N_TARGETS {int(judge.N_TARGETS)}   // == DWC1_REACH_TARGETS",
        "// f64 env tables (arm_lowering.joint_limits / velocity_limits): the",
        "// python env slews and clips with these, the physics with the f32 ones",
        "DW_MODEL_CONST double DW_ENV_LIMIT_LOWER_F64[DW_J] = {" + f64row(lim[:, 0]) + "};",
        "DW_MODEL_CONST double DW_ENV_LIMIT_UPPER_F64[DW_J] = {" + f64row(lim[:, 1]) + "};",
        "DW_MODEL_CONST double DW_ENV_VELOCITY_LIMIT_F64[DW_J] = {" + f64row(vlim) + "};",
        "DW_MODEL_CONST double DW_ENV_MAX_TARGET_INCREMENT_F64[DW_J] = {"
        + f64row(vlim * al.CONTROL_DT) + "};",
        f"// reward v{int(reward_mod.VERSION)} (walk/env/arm_reward.py) -- the kernel's DW_RW_* block",
        f"#define DW_RW_VERSION {int(reward_mod.VERSION)}",
        *[f"#define DW_RW_{name} {float(getattr(reward_mod, name))!r}"
          for name in reward_mod.CONSTANT_NAMES],
        *[f"#define DW_RW_N_{name} {len(getattr(reward_mod, name))}\n"
          f"DW_MODEL_CONST double DW_RW_{name}[{len(getattr(reward_mod, name))}] = {{"
          + f64row(getattr(reward_mod, name)) + "};"
          for name in reward_mod.TABLE_NAMES],
        "// FROZEN judge clause thresholds (walk/eval/arm_reach_judge.py) for the",
        "// in-kernel judge-shadow counters and the proxy termination",
        f"#define DW_GATE_LIMIT_TOL_RAD {float(judge.LIMIT_TOL_RAD)!r}",
        f"#define DW_GATE_SPEED_TOL_FRAC {float(judge.SPEED_TOL_FRAC)!r}",
        f"#define DW_GATE_FLOOR_MARGIN_FRAC {float(judge.FLOOR_MARGIN_FRAC)!r}",
        f"#define DW_GATE_COLUMN_RADIUS_FRAC {float(judge.COLUMN_RADIUS_FRAC)!r}",
        f"#define DW_GATE_COLUMN_HEIGHT_FRAC {float(judge.COLUMN_HEIGHT_FRAC)!r}",
        "// placeholder pairs: link_1 (yaws only, box ~0.7 m above the floor)",
        f"DW_MODEL_CONST unsigned DW_PAIR_BODY_A[DW_PAIRS] = {{{al.PLACEHOLDER_PAIR_BODY}u,{al.PLACEHOLDER_PAIR_BODY}u}};",
        "DW_MODEL_CONST unsigned DW_PAIR_BODY_B[DW_PAIRS] = {0u,0u};",
        "DW_MODEL_CONST float DW_PAIR_MU[DW_PAIRS] = " + row([0.6, 0.6]) + ";",
        "DW_MODEL_CONST float DW_FOOT_VERTICES[DW_PAIRS][DW_FOOT_VERTS][3] = {"
        + ",".join("{" + ",".join(row(v) for v in verts) + "}"
                   for _ in range(2)) + "};",
        "// ---- host-side contract pins (target sampler + judge episode shape;",
        "// header-drift pinned so a python change must regenerate this header) ----",
        f'#define DW_ARM_VARIANT "{variant}"',
        "DW_MODEL_CONST double DW_ARM_HOME_TIP[3] = {" + f64row(home_tip) + "};",
        "DW_MODEL_CONST double DW_ARM_TARGET_JOINT_BOX[DW_J][2] = {"
        + ",".join("{" + f"{float(a)!r},{float(b)!r}" + "}"
                   for a, b in env_mod.TARGET_JOINT_BOX) + "};",
        "// feasibility tables (arm_lowering.inertia_scan over pose_grid)",
        "DW_MODEL_CONST float DW_ARM_INERTIA_MAX[DW_J] = " + row(i_max) + ";",
        "DW_MODEL_CONST float DW_ARM_INERTIA_MIN[DW_J] = " + row(i_min) + ";",
        "DW_MODEL_CONST float DW_ARM_TAU_HOLD[DW_J] = " + row(tau_hold) + ";",
        "// FROZEN judge episode shape (walk/eval/arm_reach_judge.py)",
        f"#define DW_ARM_JUDGE_EPISODE_S {float(judge.EPISODE_SECONDS)!r}",
        f"#define DW_ARM_JUDGE_ACQ_HOLD_S {float(judge.ACQ_HOLD_S)!r}",
        "DW_MODEL_CONST double DW_ARM_JUDGE_TIER_RADIUS_FRAC[3] = {"
        + f64row(judge.TIER_RADIUS_FRAC) + "};",
        "#endif",
        "",
    ]
    assert math.isfinite(float(al.reach(s)))
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--variant", default="kr240", choices=("kr240", "lite"))
    parser.add_argument("--output", type=Path, default=None)
    args = parser.parse_args()
    al = load_lowering()
    text = emit(al, args.variant)
    out = args.output or default_output(args.variant)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    print(f"wrote {out} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
