"""Generate humanoid/include/duck_model.h from the pinned H0 lowering.

The humanoid twin of generate_model.py (which is UNTOUCHED and still owns
the duck header): emits the same DW_* macro/table surface the single-source
kernel (src/duck_cuda_kernel.h) consumes, with H0 humanoid values from
humanoid/h0_lowering.py -- every constant rounded once to float32. The
emitted header is committed and drift-checked by
humanoid/tests/test_humanoid_serial_parity.py.

The file is deliberately named duck_model.h: the kernel includes
"duck_model.h", and the humanoid serial build (see
walk/env/humanoid_cuda_lane.py) passes -Ihumanoid/include AHEAD of
-Iexperimental/duck_cuda/include so this header shadows the duck's without
touching any kernel source. The duck build never sees humanoid/include.

PHYSICS-ONLY HEADER. The kernel's device policy layer (dw_policy_observe /
dw_policy_reward / dw_step_policy_env) compiles against this header but is
NOT valid for the humanoid: its 58-wide observation layout hardcodes the
duck's 14-joint offsets, DW_REF_GAIT below is an all-zero placeholder (no
humanoid reference gait exists), and the flat.py-derived termination and
phase-clock constants are the duck's. Phase 1 uses only dwc1_create /
dwc1_step / dwc1_read / dwc1_reset / dwc1_set_state / dwc1_query, which
never touch the policy layer (see humanoid/FEASIBILITY.md sections 1.4, 2).

Effort caps: the kernel consumes the per-joint DW_EFFORT_CAP_TABLE
(authored H0 tiers 180/140/70, world/crates/sim/src/humanoid.rs:778-784);
the scalar DW_EFFORT_CAP is still emitted as the MINIMUM tier (70) for
diagnostics/back-compat (dwc1_info reports it). The duck generator emits a
uniform table equal to its scalar cap, so duck builds are bit-identical.

Usage: .venv/bin/python -B experimental/duck_cuda/tools/generate_model_humanoid.py \
           [--output PATH]     (default: <repo>/humanoid/include/duck_model.h)
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[3]
DEFAULT_OUTPUT = ROOT / "humanoid" / "include" / "duck_model.h"


def f32(x) -> str:
    """Exact float32 C literal (9 significant digits round-trips binary32)."""
    v = float(np.float32(x))
    if v == int(v) and abs(v) < 1e9:
        return f"{v:.1f}f"
    return f"{np.float32(x):.9g}f"


def row(values) -> str:
    return "{" + ",".join(f32(v) for v in values) + "}"


def load_lowering():
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))
    if str(ROOT / "humanoid") not in sys.path:
        sys.path.insert(0, str(ROOT / "humanoid"))
    import h0_lowering as h0  # noqa: PLC0415
    return h0


def emit(h0) -> str:
    from walk.env import flat  # noqa: PLC0415  (compile-only policy pins)
    from walk.env import reward as reward_mod  # noqa: PLC0415

    J, B = h0.J, h0.B
    assert (J, B) == (12, 14)
    n, q = 6 + J, 7 + J
    jrows, maxrows = 3 * J, 3 * J + 3 * 2 * 4
    masses = [b[3] if i else 0.0 for i, b in enumerate(h0.BODIES)]
    inertias = [(0.0, 0.0, 0.0) if i == 0 else h0.box_inertia(b[3], b[2])
                for i, b in enumerate(h0.BODIES)]
    reset_q = h0.reset_qpos()
    verts = h0.foot_vertices()
    caps = list(h0.EFFORT)

    lines = [
        "// GENERATED by experimental/duck_cuda/tools/generate_model_humanoid.py"
        " -- DO NOT EDIT.",
        "// H0 humanoid (B14/J12/P2) lowering, z-up frame; every constant",
        "// rounded once to float32. Sources cited in humanoid/h0_lowering.py.",
        "// Shadows the duck header by include order (humanoid builds only);",
        "// PHYSICS ONLY -- the kernel's policy layer is NOT valid for this",
        "// model (see generate_model_humanoid.py docstring).",
        "// Drift-checked by humanoid/tests/test_humanoid_serial_parity.py.",
        "#ifndef DUCK_MODEL_H",
        "#define DUCK_MODEL_H",
        "#if defined(__CUDACC__)",
        "#define DW_MODEL_CONST static __constant__ const",
        "#else",
        "#define DW_MODEL_CONST static const",
        "#endif",
        f"#define DW_B {B}   // bodies: floor 0, pelvis root 1, hinge children j+2",
        f"#define DW_J {J}   // hinge joints",
        f"#define DW_N {n}   // generalized dofs (6 root + J)",
        f"#define DW_Q {q}   // qpos width (root xyz + quat xyzw + J)",
        f"#define DW_JROWS {jrows}        // 3*J joint row slots",
        "#define DW_PAIRS 2         // foot-vs-floor contact pairs (L, R)",
        "#define DW_MAXPOINTS 4     // manifold points per pair",
        f"#define DW_MAXROWS {maxrows}      // 3*J + 3*DW_PAIRS*DW_MAXPOINTS",
        "#define DW_FOOT_VERTS 8    // exact box corners (single-OBB feet)",
        f"#define DW_DT {f32(h0.SIM_DT)}  // authored 1/120 x substeps 2 -> 1/240",
        f"#define DW_GRAVITY_Z {f32(-h0.GRAVITY)}  // authored -20 (y-up) -> z-up",
        "// Duck flat.py gait-clock pins: compile-only for the (invalid-for-",
        "// humanoid) policy layer; Phase 2 replaces them.",
        f"#define DW_PHASE_HZ_BASE {float(flat.PHASE_HZ_BASE)!r}",
        f"#define DW_PHASE_HZ_PER_MPS {float(flat.PHASE_HZ_PER_MPS)!r}",
        f"#define DW_ARMATURE {f32(h0.ARMATURE)}       // not authored for H0",
        f"#define DW_DAMPING {f32(h0.PASSIVE_DAMPING)} // H0 damping is kv, not passive",
        f"#define DW_FRICTION_LOSS {f32(h0.FRICTION_LOSS)}  // not authored for H0",
        f"#define DW_KP {f32(h0.KP)}",
        f"#define DW_KV {f32(h0.KV)}",
        "// Scalar cap = MIN of the authored per-joint tiers (180/140/70),",
        "// kept for diagnostics/back-compat; the kernel clamps with the",
        "// per-joint DW_EFFORT_CAP_TABLE below.",
        f"#define DW_EFFORT_CAP {f32(min(caps))}",
        "DW_MODEL_CONST float DW_EFFORT_CAP_TABLE[DW_J] = " + row(caps) + ";",
        f"#define DW_FRICTION_D0 {f32(0.9)}",
        f"#define DW_FRICTION_DWIDTH {f32(0.95)}",
        f"#define DW_FRICTION_TIMECONST {f32(0.02)}",
        f"#define DW_LIMIT_MARGIN {f32(0.0)}",
        f"#define DW_LIMIT_TIMECONST {f32(0.02)}",
        f"#define DW_LIMIT_DAMPRATIO {f32(1.0)}",
        "DW_MODEL_CONST float DW_LIMIT_SOLIMP[5] = "
        + row([0.9, 0.95, 0.001, 0.5, 2.0]) + ";",
        "DW_MODEL_CONST float DW_BODY_MASS[DW_B] = " + row(masses) + ";",
        "DW_MODEL_CONST float DW_BODY_INERTIA[DW_B][3] = {"
        + ",".join(row(i3) for i3 in inertias) + "};",
        "DW_MODEL_CONST unsigned DW_HINGE_PARENT[DW_J] = {"
        + ",".join(str(j[1]) for j in h0.JOINTS) + "};",
        "DW_MODEL_CONST float DW_HINGE_AP[DW_J][3] = {"
        + ",".join(row(j[2]) for j in h0.JOINTS) + "};",
        "DW_MODEL_CONST float DW_HINGE_AC[DW_J][3] = {"
        + ",".join(row(j[3]) for j in h0.JOINTS) + "};",
        "DW_MODEL_CONST float DW_HINGE_AXIS[DW_J][3] = {"
        + ",".join(row(h0.AXIS) for _ in h0.JOINTS) + "};",
        "DW_MODEL_CONST float DW_HINGE_REF[DW_J][4] = {"
        + ",".join(row(h0.REFERENCE_XYZW) for _ in h0.JOINTS) + "};",
        "DW_MODEL_CONST float DW_LIMIT_LOWER[DW_J] = "
        + row([j[4] for j in h0.JOINTS]) + ";",
        "DW_MODEL_CONST float DW_LIMIT_UPPER[DW_J] = "
        + row([j[5] for j in h0.JOINTS]) + ";",
        "// identity source->principal: H0 bodies are zero-offset principal",
        "// boxes (humanoid.rs:710-721), unlike the duck.",
        "DW_MODEL_CONST float DW_ROOT_COM[3] = " + row([0.0, 0.0, 0.0]) + ";",
        "DW_MODEL_CONST float DW_ROOT_QPC[4] = "
        + row([0.0, 0.0, 0.0, 1.0]) + ";",
        "DW_MODEL_CONST float DW_REFERENCE_QPOS[DW_Q] = " + row(reset_q) + ";",
        "DW_MODEL_CONST float DW_INITIAL_QPOS[DW_Q] = " + row(reset_q) + ";",
        "DW_MODEL_CONST float DW_INITIAL_VEL[DW_N] = "
        + row([0.0] * n) + ";",
        "DW_MODEL_CONST float DW_HOME_TARGETS[DW_J] = "
        + row(h0.HOME_TARGETS) + ";",
        "DW_MODEL_CONST double DW_HOME_TARGETS_F64[DW_J] = {"
        + ",".join(f"{float(x):.17g}" for x in h0.HOME_TARGETS) + "};",
        "// Duck reward.py pins: compile-only (policy layer invalid, above).",
        *[f"#define DW_RW_{name} {float(getattr(reward_mod, name))!r}"
          for name in [
              "W_TRACK", "TRACK_SIGMA_SQ", "TRACK_EMA_S", "W_ALIVE",
              "W_LATERAL", "W_ACTION_RATE", "W_TORQUE", "W_AIR_TIME",
              "AIR_TIME_MIN", "AIR_TIME_MAX", "PLACEMENT_MIN_M",
              "OPP_SUPPORT_FRAC", "W_CHATTER", "CHATTER_MAX_S", "W_FLICKER",
              "STANCE_MIN_S", "W_CLEARANCE", "CLEARANCE_M",
              "W_DOUBLE_SUPPORT", "DOUBLE_SUPPORT_GRACE", "W_ALTERNATE",
              "W_SAME_FOOT", "W_PHASE"]],
        f"#define DW_RW_TICKS_FULL {int(reward_mod.TICKS_FULL)}u",
        f"#define DW_REF_BINS {int(reward_mod.REF_BINS)}",
        f"#define DW_IMIT_W {float(reward_mod.W_IMIT)!r}",
        f"#define DW_IMIT_SIGMA_SQ {float(reward_mod.IMIT_SIGMA_SQ)!r}",
        "// ALL-ZERO placeholder: no humanoid reference gait exists (Phase 2).",
        "DW_MODEL_CONST double DW_REF_GAIT[DW_REF_BINS][DW_J] = {"
        + ",".join("{" + ",".join("0.0" for _ in range(J)) + "}"
                   for _ in range(int(reward_mod.REF_BINS))) + "};",
        "DW_MODEL_CONST unsigned DW_PAIR_BODY_A[DW_PAIRS] = {"
        + ",".join(f"{b}u" for b in h0.FOOT_BODIES) + "};",
        "DW_MODEL_CONST unsigned DW_PAIR_BODY_B[DW_PAIRS] = {0u,0u};",
        "DW_MODEL_CONST float DW_PAIR_MU[DW_PAIRS] = "
        + row([h0.FRICTION, h0.FRICTION]) + ";",
        "DW_MODEL_CONST float DW_FOOT_VERTICES[DW_PAIRS][DW_FOOT_VERTS][3] = {"
        + ",".join("{" + ",".join(row(v) for v in verts) + "}"
                   for _ in range(2)) + "};",
        "#endif",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    text = emit(load_lowering())
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text)
    print(f"wrote {args.output} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
