// GENERATED by experimental/duck_cuda/tools/generate_model_arm.py --variant lite -- DO NOT EDIT.
// Fixed-base 6-axis arm, variant 'lite' (B8/J6/P2 placeholder pairs), z-up frame,
// arm/arm_lowering.py (URDF-sourced KR240; 'lite' = 0.5 x length,
// 1/8 x mass Froude scaling). Every constant rounded once to float32.
// Shadows the duck header by include order (arm builds only).
// PHYSICS ONLY -- the kernel's device policy layer is NOT valid for
// this model (see generate_model_arm.py docstring; DW_ARM_* pins the
// python-side contract). FIXED BASE: DW_HINGE_PARENT[0] == 0, the
// static floor; body 1 is a decoupled phantom root (FEASIBILITY.md 1).
// Drift-checked by arm/tests/test_arm_serial_parity.py.
#ifndef DUCK_MODEL_H
#define DUCK_MODEL_H
#if defined(__CUDACC__)
#define DW_MODEL_CONST static __constant__ const
#else
#define DW_MODEL_CONST static const
#endif
#define DW_B 8   // bodies: floor 0 (+ fused base_link), phantom root 1, link_k = body k+1
#define DW_J 6   // revolute joints a1..a6
#define DW_N 12   // generalized dofs (6 phantom root + J)
#define DW_Q 13   // qpos width (root xyz + quat xyzw + J)
#define DW_JROWS 18        // 3*J joint row slots
#define DW_PAIRS 2         // kernel-mandated pairs: PLACEHOLDERS on link_1, never in contact
#define DW_MAXPOINTS 4
#define DW_MAXROWS 42      // 3*J + 3*DW_PAIRS*DW_MAXPOINTS
#define DW_FOOT_VERTS 8    // placeholder box corners
#define DW_DT 0.00200000009f  // duck-stack tick; 10 per 0.02 s step
#define DW_GRAVITY_Z -9.81000042f  // authored -9.81 (KR240 contract); humanoid is -20, NOT unified
// gait clock: unused by the arm (kernel compile requirement)
#define DW_PHASE_HZ_BASE 0.0
#define DW_PHASE_HZ_PER_MPS 0.0
#define DW_ARMATURE 0.0f       // not authored by the URDF
#define DW_DAMPING 0.0f  // URDF joint damping folded into DW_KV_TABLE
#define DW_FRICTION_LOSS 0.0f  // URDF Coulomb friction (<= 0.1 % of effort) dropped
// fp32 certificates, SCALE-AWARE: the certified humanoid lane's
// relative pins (1.75e-4 / 7e-3 / 2.4e-2 on its 2.72 N*s per-tick
// weight impulse) applied to this arm's reference impulse
// max(effort)*dt = 1.5 N*m*s.
#define DW_SOLVE_TOLERANCE 9.64999999e-05f
#define DW_MOMENTUM_TOLERANCE 0.00386000006f
#define DW_APGD_BUDGET 8192u
#define DW_TIER_CEILING 0.0131999999f
// PD gains AUTHORED BY THE LOWERING (arm_lowering.gains: bandwidth
// sqrt(kp/I_max) >= 3 x the judge's 0.625 Hz target-change rate,
// gravity sag <= 0.01 rad at full horizontal extension, full torque
// within 0.1 rad, capped at sqrt(kp/I_min)*dt <= 0.25; kv = 2*0.7*
// sqrt(kp*I_max) + URDF damping). Scalars = MIN of the tables
// (dwc1_info summary only; the kernel consumes the tables).
#define DW_KP 58.7000008f
#define DW_KV 1.19000006f
DW_MODEL_CONST float DW_KP_TABLE[DW_J] = {9760.0f,41900.0f,11600.0f,765.0f,1150.0f,58.7000008f};
DW_MODEL_CONST float DW_KV_TABLE[DW_J] = {1160.0f,1960.0f,421.0f,13.3999996f,13.6999998f,1.19000006f};
#define DW_EFFORT_CAP 75.0f
DW_MODEL_CONST float DW_EFFORT_CAP_TABLE[DW_J] = {750.0f,750.0f,562.5f,187.5f,125.0f,75.0f};
#define DW_FRICTION_D0 0.899999976f
#define DW_FRICTION_DWIDTH 0.949999988f
#define DW_FRICTION_TIMECONST 0.0199999996f
#define DW_LIMIT_MARGIN 0.0f
#define DW_LIMIT_TIMECONST 0.0199999996f
#define DW_LIMIT_DAMPRATIO 1.0f
DW_MODEL_CONST float DW_LIMIT_SOLIMP[5] = {0.899999976f,0.949999988f,0.00100000005f,0.5f,2.0f};
// body 1 = phantom root carrying base_link's mass/inertia (decoupled)
DW_MODEL_CONST float DW_BODY_MASS[DW_B] = {0.0f,53.75f,32.5f,22.5f,15.625f,8.125f,4.75f,2.75f};
DW_MODEL_CONST float DW_BODY_INERTIA[DW_B][3] = {{0.0f,0.0f,0.0f},{1.50640655f,2.21032739f,3.21108103f},{0.780824423f,1.79692912f,1.57416356f},{0.362518936f,1.96442986f,1.89482725f},{0.217193067f,0.909876227f,0.931970358f},{0.0224545617f,0.043908f,0.0439090319f},{0.0223395322f,0.0220944379f,0.0299740937f},{0.00375531241f,0.00194528128f,0.00194581249f}};
// joint 0 parent = 0: the STATIC FLOOR (structural weld)
DW_MODEL_CONST unsigned DW_HINGE_PARENT[DW_J] = {0,2,3,4,5,6};
DW_MODEL_CONST float DW_HINGE_AP[DW_J][3] = {{0.0f,0.0f,0.430312514f},{-0.208188504f,0.00143449998f,-0.0776494965f},{0.378290504f,0.133366004f,0.00151450001f},{0.521479547f,-0.0380900018f,-0.0039295f},{-0.0530409999f,0.0f,1.75000005e-05f},{-0.0293199997f,-0.00927050039f,1.49999996e-05f}};
DW_MODEL_CONST float DW_HINGE_AC[DW_J][3] = {{0.0149365002f,0.00143449998f,-0.0776494965f},{-0.354834497f,0.133366004f,0.00151450001f},{-0.116020501f,-0.0380900018f,0.0222079996f},{-0.0530409999f,-0.0f,1.75000005e-05f},{-0.0293199997f,-0.00927050039f,1.49999996e-05f},{0.128443494f,-0.0f,2.09999998e-05f}};
DW_MODEL_CONST float DW_HINGE_AXIS[DW_J][3] = {{2.15390738e-15f,-4.64102072e-08f,-1.0f},{-4.64102072e-08f,1.0f,-4.64102072e-08f},{0.0f,1.0f,0.0f},{-1.0f,-4.64102072e-08f,0.0f},{4.64102072e-08f,-1.0f,0.0f},{-1.0f,-4.64102072e-08f,0.0f}};
DW_MODEL_CONST float DW_HINGE_REF[DW_J][4] = {{-2.32051036e-08f,1.0f,-2.32051036e-08f,5.38476844e-16f},{-2.32051036e-08f,1.0f,-2.32051036e-08f,5.38476844e-16f},{0.0f,0.0f,0.0f,1.0f},{-0.0f,-0.0f,-1.0f,2.32051036e-08f},{-0.0f,-0.0f,-1.0f,2.32051036e-08f},{-0.0f,-0.0f,-1.0f,2.32051036e-08f}};
DW_MODEL_CONST float DW_LIMIT_LOWER[DW_J] = {-3.22885919f,-2.70526004f,-2.26892805f,-6.10865259f,-2.26892805f,-6.10865259f};
DW_MODEL_CONST float DW_LIMIT_UPPER[DW_J] = {3.22885919f,0.610865176f,2.68780708f,6.10865259f,2.26892805f,6.10865259f};
// phantom root source->principal: base_link COM offset, no rotation
DW_MODEL_CONST float DW_ROOT_COM[3] = {-0.070871003f,0.0f,0.1187905f};
DW_MODEL_CONST float DW_ROOT_QPC[4] = {0.0f,0.0f,0.0f,1.0f};
DW_MODEL_CONST float DW_REFERENCE_QPOS[DW_Q] = {0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,1.0f,0.0f,-1.20000005f,1.60000002f,0.0f,-0.400000006f,0.0f};
DW_MODEL_CONST float DW_INITIAL_QPOS[DW_Q] = {0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,1.0f,0.0f,-1.20000005f,1.60000002f,0.0f,-0.400000006f,0.0f};
DW_MODEL_CONST float DW_INITIAL_VEL[DW_N] = {0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f};
DW_MODEL_CONST float DW_HOME_TARGETS[DW_J] = {0.0f,-1.20000005f,1.60000002f,0.0f,-0.400000006f,0.0f};
DW_MODEL_CONST double DW_HOME_TARGETS_F64[DW_J] = {0,-1.2,1.6000000000000001,0,-0.40000000000000002,0};
// ---- kernel compile requirements (locomotion policy layer; NOT
// valid for the arm, never called by the arm lanes) ----
#define DW_RW_W_TRACK 0.0
#define DW_RW_W_ALIVE 0.0
#define DW_RW_W_LATERAL 0.0
#define DW_RW_W_ACTION_RATE 0.0
#define DW_RW_W_TORQUE 0.0
#define DW_RW_W_AIR_TIME 0.0
#define DW_RW_AIR_TIME_MIN 0.0
#define DW_RW_AIR_TIME_MAX 0.0
#define DW_RW_PLACEMENT_MIN_M 0.0
#define DW_RW_OPP_SUPPORT_FRAC 0.0
#define DW_RW_W_CHATTER 0.0
#define DW_RW_CHATTER_MAX_S 0.0
#define DW_RW_W_FLICKER 0.0
#define DW_RW_STANCE_MIN_S 0.0
#define DW_RW_W_CLEARANCE 0.0
#define DW_RW_CLEARANCE_M 0.0
#define DW_RW_W_DOUBLE_SUPPORT 0.0
#define DW_RW_DOUBLE_SUPPORT_GRACE 0.0
#define DW_RW_W_ALTERNATE 0.0
#define DW_RW_W_SAME_FOOT 0.0
#define DW_RW_W_PHASE 0.0
#define DW_RW_TRACK_SIGMA_SQ 1.0
#define DW_RW_TRACK_EMA_S 1.0    // nonzero: the kernel divides by it
#define DW_RW_TICKS_FULL 10u
#define DW_REF_BINS 1
#define DW_IMIT_W 0.0
#define DW_IMIT_SIGMA_SQ 1.0
#define DW_ENV_OBS 34   // kernel layout width (memory safety); the arm's obs is 27, python-side
#define DW_ENV_ACT 6
#define DW_ENV_TICKS_PER_STEP 10u
#define DW_ENV_CONTROL_DT 0.02
#define DW_ENV_ACTION_SCALE 0.0
#define DW_ENV_MAX_TARGET_INCREMENT 0.0
#define DW_ENV_QDOT_OBS_SCALE 0.0
#define DW_ENV_HORIZON_STEPS 400u
#define DW_ENV_MIN_HEIGHT_FRACTION -1e30
#define DW_ENV_MAX_TILT_RAD 3.141592653589793
#define DW_ENV_COS_MAX_TILT -1.0
#define DW_ENV_UP_AXIS 2
DW_MODEL_CONST double DW_ENV_COMMANDS_MPS[3] = {0.0,0.0,0.0};
#define DW_GATE_SWING_MIN_S 0.0
#define DW_GATE_SWING_MAX_S 0.0
#define DW_GATE_CLEARANCE_M 0.0f
#define DW_GATE_CLEARANCE_MIN_S 0.0
#define DW_GATE_PLACEMENT_MIN_M 0.0f
DW_MODEL_CONST double DW_REF_GAIT[DW_REF_BINS][DW_J] = {{0.0,0.0,0.0,0.0,0.0,0.0}};
// placeholder pairs: link_1 (yaws only, box ~0.7 m above the floor)
DW_MODEL_CONST unsigned DW_PAIR_BODY_A[DW_PAIRS] = {2u,2u};
DW_MODEL_CONST unsigned DW_PAIR_BODY_B[DW_PAIRS] = {0u,0u};
DW_MODEL_CONST float DW_PAIR_MU[DW_PAIRS] = {0.600000024f,0.600000024f};
DW_MODEL_CONST float DW_FOOT_VERTICES[DW_PAIRS][DW_FOOT_VERTS][3] = {{{-0.0500000007f,-0.0500000007f,-0.0500000007f},{0.0500000007f,-0.0500000007f,-0.0500000007f},{-0.0500000007f,0.0500000007f,-0.0500000007f},{0.0500000007f,0.0500000007f,-0.0500000007f},{-0.0500000007f,-0.0500000007f,0.0500000007f},{0.0500000007f,-0.0500000007f,0.0500000007f},{-0.0500000007f,0.0500000007f,0.0500000007f},{0.0500000007f,0.0500000007f,0.0500000007f}},{{-0.0500000007f,-0.0500000007f,-0.0500000007f},{0.0500000007f,-0.0500000007f,-0.0500000007f},{-0.0500000007f,0.0500000007f,-0.0500000007f},{0.0500000007f,0.0500000007f,-0.0500000007f},{-0.0500000007f,-0.0500000007f,0.0500000007f},{0.0500000007f,-0.0500000007f,0.0500000007f},{-0.0500000007f,0.0500000007f,0.0500000007f},{0.0500000007f,0.0500000007f,0.0500000007f}}};
// ---- ARM CONTRACT PINS (python-side env/reward/judge; header-drift
// pinned so a python change must regenerate this header) ----
#define DW_ARM_VARIANT "lite"
#define DW_ARM_OBS 27
#define DW_ARM_ACT 6
#define DW_ARM_HORIZON_STEPS 400u
#define DW_ARM_QDOT_OBS_SCALE 0.25
#define DW_ARM_ACQ_HOLD_STEPS 14
#define DW_ARM_REACH_M 1.7307500499999986
DW_MODEL_CONST double DW_ARM_HOME_TIP[3] = {1.2027765365585052,2.8426052592691958e-08,0.8412852104762929};
DW_MODEL_CONST float DW_ARM_VELOCITY_LIMIT[DW_J] = {2.5423162f,2.32017303f,2.46826792f,4.19605637f,3.18406653f,5.0846324f};
DW_MODEL_CONST double DW_ARM_MAX_TARGET_INCREMENT[DW_J] = {0.05084632329457854,0.04640345825129846,0.049365358852061426,0.0839211298474943,0.06368132960687929,0.10169264658915708};
DW_MODEL_CONST double DW_ARM_TARGET_JOINT_BOX[DW_J][2] = {{-1.2,1.2},{-2.0,0.2},{0.4,2.2},{-0.6,0.6},{-1.6,1.6},{0.0,0.0}};
// feasibility tables (arm_lowering.inertia_scan over pose_grid)
DW_MODEL_CONST float DW_ARM_INERTIA_MAX[DW_J] = {70.3448334f,46.6543083f,7.70740509f,0.101004153f,0.0734918788f,0.00375531381f};
DW_MODEL_CONST float DW_ARM_INERTIA_MIN[DW_J] = {5.9977622f,17.4956512f,6.90274334f,0.0489576347f,0.0734918788f,0.00375531381f};
DW_MODEL_CONST float DW_ARM_TAU_HOLD[DW_J] = {2.51351557e-05f,419.173676f,116.104195f,0.431982517f,4.83132315f,7.86454998e-11f};
// reward v1 (walk/env/arm_reward.py)
#define DW_ARM_RW_W_DIST 1.0
#define DW_ARM_RW_DIST_SIGMA_FRAC 0.1
#define DW_ARM_RW_W_LIN 0.5
#define DW_ARM_RW_W_ACQUIRE 10.0
#define DW_ARM_RW_W_ACTION_RATE 0.05
#define DW_ARM_RW_W_TORQUE 0.05
#define DW_ARM_RW_W_SPEED 0.5
#define DW_ARM_RW_SPEED_FRAC 0.9
#define DW_ARM_RW_W_PROXY 5.0
// FROZEN judge (walk/eval/arm_reach_judge.py)
#define DW_ARM_JUDGE_EPISODE_S 8.0
#define DW_ARM_JUDGE_N_TARGETS 5
#define DW_ARM_JUDGE_ACQ_RADIUS_M 0.015
#define DW_ARM_JUDGE_ACQ_HOLD_S 0.25
DW_MODEL_CONST double DW_ARM_JUDGE_TIER_RADIUS_FRAC[3] = {0.15,0.3,0.4};
#define DW_ARM_JUDGE_LIMIT_TOL_RAD 0.01
#define DW_ARM_JUDGE_SPEED_TOL_FRAC 1.0
#define DW_ARM_JUDGE_FLOOR_MARGIN_FRAC 0.05
#define DW_ARM_JUDGE_COLUMN_RADIUS_FRAC 0.2
#define DW_ARM_JUDGE_COLUMN_HEIGHT_FRAC 0.4
#endif
